# nginx proxy address - http://172.17.0.1:5230

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  memos:
    image: memos/memos:latest
    container_name: memos-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - memos
    ports:
      - "5230:5230"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./rootfs/config/memos:/config
      - ./rootfs/data/memos:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5230"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  memos:
    external: false
