# nginx proxy address - http://172.17.0.1:5230

name: memos
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: neosmemo/memos:latest
    pull_policy: always
    container_name: memos-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - memos
    ports:
      - "172.17.0.1:5230:5230"
    environment:
      TZ: ${TZ:-America/New_York}
      MEMOS_MODE: prod
      MEMOS_PORT: 5230
    volumes:
      - ./volumes/data/memos:/var/opt/memos
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5230/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  memos:
    name: memos
    external: false
