# nginx proxy address - http://172.17.0.1:5230

name: memos
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  app:
    image: neosmemo/memos:latest
    pull_policy: always
    container_name: memos-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - memos
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:5230:5230"
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: memos-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      MEMOS_MODE: prod
      MEMOS_PORT: 5230
    volumes:
      - ./volumes/data/memos:/var/opt/memos
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5230/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://memos-app:5230'
      - 'cloudflare.hostname=memos.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.memos-app.entrypoints=http'
      - 'traefik.http.routers.memos-app-secure.tls=true'
      - 'traefik.http.routers.memos-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.memos-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.memos-app.middlewares=memos-app-https-redirect'
      - 'traefik.http.routers.memos-app-secure.entrypoints=https'
      - 'traefik.http.routers.memos-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.memos-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.memos-app-secure.service=memos-app'
      - 'traefik.http.services.memos-app.loadbalancer.server.port=5230'

networks:
  memos:
    name: memos
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
